"""adding foreign keys

Revision ID: 58308b80266e
Revises: 927a409892a1
Create Date: 2023-04-12 13:22:43.743328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58308b80266e'
down_revision = '927a409892a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_leases_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_leases_apartment_id_apartments'), 'apartments', ['apartment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leases_apartment_id_apartments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_leases_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('apartment_id')

    # ### end Alembic commands ###
